# Generated by Django 4.2 on 2023-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainfeed",
            name="slug",
            field=models.SlugField(
                help_text="Слаг RSS-канала", unique=True, verbose_name="Слаг"
            ),
        ),
    ]
