repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
        args: [--directory=api/]
      - id: poetry-lock
        args: [--directory=api/]

-   repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
        args: [--config=api/pyproject.toml]

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config=api/.flake8]

-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--sp=api/pyproject.toml]
