[tool.poetry]
name = "openrss-api"
version = "0.1.0"
description = "OpenRSS API"
authors = ["Mark Likhachev <gogomecourier@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "4.1.7"
djangorestframework = "3.14.0"

[tool.black]
extend-exclude = '''
(
  migrations/
)
'''

[tool.isort]
profile = "black"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
